// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/lib/js/src/Cn.bs.js");
var React = require("react");
var Layout$Emotions = require("./Layout.bs.js");
var ComponentStyles$Emotions = require("./ComponentStyles.bs.js");

function Component(Props) {
  var size = Props.size;
  var animate = Props.animate;
  return React.createElement(Layout$Emotions.make, {
              children: React.createElement("div", {
                    className: ComponentStyles$Emotions.container
                  }, React.createElement("div", {
                        className: ComponentStyles$Emotions.shape
                      }, React.createElement("div", {
                            className: Cn.make({
                                  hd: ComponentStyles$Emotions.text(size),
                                  tl: {
                                    hd: Cn.ifTrue(ComponentStyles$Emotions.animated, animate),
                                    tl: /* [] */0
                                  }
                                })
                          }, "Hi!")), React.createElement("div", {
                        className: ComponentStyles$Emotions.note
                      }, "↑ Hover it ↑"), React.createElement("h2", undefined, "Grid"), React.createElement("div", {
                        className: ComponentStyles$Emotions.grid
                      }, React.createElement("div", {
                            className: Cn.make({
                                  hd: ComponentStyles$Emotions.gridItem,
                                  tl: {
                                    hd: ComponentStyles$Emotions.gridItem1,
                                    tl: /* [] */0
                                  }
                                })
                          }, "1"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "2"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "3"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "4"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "5"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "6"), React.createElement("div", {
                            className: ComponentStyles$Emotions.gridItem
                          }, "7")))
            });
}

var Css;

var make = Component;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
