// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Emotion$Emotions = require("./Emotion.bs.js");

Emotion$Emotions.$$global("html", {
      hd: Emotion$Emotions.minHeight({
            NAME: "pct",
            VAL: 100
          }),
      tl: {
        hd: Emotion$Emotions.fontFamily("Tahoma, sans-serif"),
        tl: /* [] */0
      }
    });

Emotion$Emotions.$$global("html, body, #app", {
      hd: Emotion$Emotions.display("grid"),
      tl: {
        hd: Emotion$Emotions.gridTemplateRows({
              NAME: "list",
              VAL: {
                hd: {
                  NAME: "fr",
                  VAL: 1
                },
                tl: /* [] */0
              }
            }),
        tl: {
          hd: Emotion$Emotions.gridTemplateColumns({
                NAME: "list",
                VAL: {
                  hd: {
                    NAME: "fr",
                    VAL: 1
                  },
                  tl: /* [] */0
                }
              }),
          tl: {
            hd: Emotion$Emotions.gridGap("zero"),
            tl: {
              hd: Emotion$Emotions.margin("zero"),
              tl: {
                hd: Emotion$Emotions.padding("zero"),
                tl: /* [] */0
              }
            }
          }
        }
      }
    });

Emotion$Emotions.fontFace({
      hd: Emotion$Emotions.fontFamily("MyFont"),
      tl: {
        hd: Emotion$Emotions.fontWeight(400),
        tl: {
          hd: Emotion$Emotions.fontStyle("normal"),
          tl: {
            hd: Emotion$Emotions.src({
                  hd: [
                    {
                      NAME: "url",
                      VAL: "my-font.woff"
                    },
                    "woff"
                  ],
                  tl: {
                    hd: [
                      {
                        NAME: "url",
                        VAL: "my-font.woff2"
                      },
                      "woff2"
                    ],
                    tl: /* [] */0
                  }
                }),
            tl: /* [] */0
          }
        }
      }
    });

/*  Not a pure module */
