// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.bs.js");
var Component$Emotions = require("./Component.bs.js");
var GlobalStyles$Emotions = require("./GlobalStyles.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component$Emotions.make, {
          size: 30,
          animate: true
        }), "app");

/*  Not a pure module */
