// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Emotion$Emotions = require("./Emotion.bs.js");

var container = Emotion$Emotions.css(undefined, {
      hd: Emotion$Emotions.label("container"),
      tl: {
        hd: Emotion$Emotions.display("grid"),
        tl: {
          hd: Emotion$Emotions.gridTemplateRows({
                NAME: "list",
                VAL: {
                  hd: {
                    NAME: "fr",
                    VAL: 1
                  },
                  tl: {
                    hd: "maxContent",
                    tl: /* [] */0
                  }
                }
              }),
          tl: {
            hd: Emotion$Emotions.gridTemplateColumns({
                  NAME: "list",
                  VAL: {
                    hd: {
                      NAME: "fr",
                      VAL: 1
                    },
                    tl: /* [] */0
                  }
                }),
            tl: /* [] */0
          }
        }
      }
    });

var main = Emotion$Emotions.css(undefined, {
      hd: Emotion$Emotions.label("main"),
      tl: {
        hd: Emotion$Emotions.display("grid"),
        tl: {
          hd: Emotion$Emotions.alignItems("center"),
          tl: {
            hd: Emotion$Emotions.justifyItems("center"),
            tl: /* [] */0
          }
        }
      }
    });

var footer = Emotion$Emotions.css(undefined, {
      hd: Emotion$Emotions.label("footer"),
      tl: {
        hd: Emotion$Emotions.display("grid"),
        tl: {
          hd: Emotion$Emotions.alignItems("center"),
          tl: {
            hd: Emotion$Emotions.justifyItems("center"),
            tl: {
              hd: Emotion$Emotions.padding({
                    NAME: "px",
                    VAL: 20
                  }),
              tl: {
                hd: Emotion$Emotions.backgroundColor({
                      NAME: "hex",
                      VAL: "f7f7f7"
                    }),
                tl: /* [] */0
              }
            }
          }
        }
      }
    });

exports.container = container;
exports.main = main;
exports.footer = footer;
/* container Not a pure module */
