// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var React = require("react");
var Layout = require("./Layout.bs.js");
var ComponentStyles = require("./ComponentStyles.bs.js");

function Component(Props) {
  var size = Props.size;
  var animate = Props.animate;
  return React.createElement(Layout.make, {
              children: React.createElement("div", {
                    className: ComponentStyles.container
                  }, React.createElement("div", {
                        className: ComponentStyles.shape
                      }, React.createElement("div", {
                            className: Cn.make(/* :: */[
                                  ComponentStyles.text(size),
                                  /* :: */[
                                    Cn.ifTrue(ComponentStyles.animated, animate),
                                    /* [] */0
                                  ]
                                ])
                          }, "Hi!")), React.createElement("div", {
                        className: ComponentStyles.note
                      }, "↑ Hover it ↑"), React.createElement("h2", undefined, "Grid"), React.createElement("div", {
                        className: ComponentStyles.grid
                      }, React.createElement("div", {
                            className: Cn.make(/* :: */[
                                  ComponentStyles.gridItem,
                                  /* :: */[
                                    ComponentStyles.gridItem1,
                                    /* [] */0
                                  ]
                                ])
                          }, "1"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "2"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "3"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "4"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "5"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "6"), React.createElement("div", {
                            className: ComponentStyles.gridItem
                          }, "7")))
            });
}

var Css;

var make = Component;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
