// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Component = require("./Component.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var GlobalStyles = require("./GlobalStyles.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component.make, {
          size: 30,
          animate: true
        }), "app");

/*  Not a pure module */
