// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var LayoutStyles = require("./LayoutStyles.bs.js");

function Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: LayoutStyles.container
            }, React.createElement("main", {
                  className: LayoutStyles.main
                }, children), React.createElement("footer", {
                  className: LayoutStyles.footer
                }));
}

var Css;

var make = Layout;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
